get line number
Signed-off-by: Michael Crenshaw <350466+crenshaw-dev@users.noreply.github.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -51,8 +51,9 @@ jobs:
       - name: go mod tidy
         run: |
           go mod tidy
-          if ! git diff --exit-code; then
-            echo "::error file=go.sum::go.sum is out of date. Run 'go mod tidy' and commit the changes."
+          if ! diff=$(git diff --exit-code -- go.mod); then
+            line=$(echo "$diff" | sed -nr 's/@@ -([0-9]+),.*/\1/p' | head -n 1 | tr -d '\n')
+            echo "::error file=go.sum,line=$line::go.sum is out of date. Run 'go mod tidy' and commit the changes."
             exit 1
           fi
       - name: make build-installer
