chore(ci): fix indirect gh client major bump (#1757)
* chore(ci): fix indirect gh client major bump

Signed-off-by: Michael Crenshaw <350466+crenshaw-dev@users.noreply.github.com>

* fix single line hunk bug

Signed-off-by: Michael Crenshaw <350466+crenshaw-dev@users.noreply.github.com>

---------

Signed-off-by: Michael Crenshaw <350466+crenshaw-dev@users.noreply.github.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -136,11 +136,13 @@ jobs:
       - name: go mod tidy
         run: |
           go mod tidy
-          if ! diff=$(git diff --exit-code --unified=0 -- go.sum); then
-            line=$(echo "$diff" | sed -nr 's/@@ -([0-9]+),.*/\1/p' | head -n 1 | tr -d '\n')
-            echo "::error file=go.sum,line=$line::go.sum is out of date. Run 'go mod tidy' and commit the changes."
-            exit 1
-          fi
+          for file in go.mod go.sum; do
+            if ! diff=$(git diff --exit-code --unified=0 -- "$file"); then
+              line=$(echo "$diff" | sed -nr 's/^@@ -([0-9]+).*/\1/p' | head -n 1 | tr -d '\n')
+              echo "::error file=$file,line=$line::$file is out of date. Run 'go mod tidy' and commit the changes."
+              exit 1
+            fi
+          done
       - name: make mockery-gen
         run: |
           make mockery-gen
